# Annex 1
### Technologies

In [1]:
pip install pandas openpyxl

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Requirement already satisfied: pandas in c:\users\savan\appdata\roaming\python\python311\site-packages (2.1.1)
Requirement already satisfied: openpyxl in c:\users\savan\appdata\roaming\python\python311\site-packages (3.1.2)
Requirement already satisfied: numpy>=1.23.2 in c:\users\savan\appdata\roaming\python\python311\site-packages (from pandas) (1.26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\savan\appdata\roaming\python\python311\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\savan\appdata\roaming\python\python311\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\savan\appdata\roaming\python\python311\site-packages (from pandas) (2023.3)
Requirement already satisfied: et-xmlfile in c:\users\savan\appdata\roaming\python\python311\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in c:\users\savan\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import pandas as pd
from IPython.display import Markdown, display

# Load the Excel file
excel_file = 'VT_REGION1_ELC.xlsx'

# Load the specified sheet
sheet_name = 'Processes'
data_range = 'B7:H129'

# Read data from Excel, excluding the first row
df = pd.read_excel(excel_file, sheet_name=sheet_name, header=None, usecols="B:H", skiprows=7, nrows=69)

# Assign column names
df.columns = ['Technology Code', 'Technology Description', 'Activity Unit', 'Capacity Unit', 'Timeslice level (CTSLvl)', 'Sets','Vintage']

# Remove empty rows
df = df.dropna()

# Define CSS styles for the table
table_styles = [
    dict(selector="th", props=[("font-size", "14px"), ("text-align", "left"), ("background-color", "#f2f2f2"), ("padding", "8px")]),
    dict(selector="td", props=[("font-size", "14px"), ("text-align", "left"), ("padding", "8px")]),
    dict(selector="tr:hover", props=[("background-color", "#f5f5f5")]),
]

# Apply CSS styles to the HTML table
styled_table = df.style.set_table_styles(table_styles)
# Define table header
table_header = "### Table A1: Technologies comprising the power sector in SATIM.\n"

# Display table header
display(Markdown(table_header))

# Display the styled table
styled_table

FileNotFoundError: [Errno 2] No such file or directory: 'VT_REGION1_ELC.xlsx'

### Input Commodities

In [3]:
import pandas as pd
from IPython.display import Markdown, display

# Load the Excel file
excel_file = 'VT_REGION1_ELC.xlsx'

# Load the specified sheet
sheet_name = 'Commodities'
data_range = 'B7:F75'

# Read data from Excel, excluding the first row
df = pd.read_excel(excel_file, sheet_name=sheet_name, header=None, usecols="B:F", skiprows=7, nrows=69)

# Assign column names
df.columns = ['Commodity Code', 'Commodity Description', 'Commodity Unit', 'Commodity Set(Csets)', 'Timeslice level (CTSLvl)']

# Remove empty rows
df = df.dropna()

# Define CSS styles for the table
table_styles = [
    dict(selector="th", props=[("font-size", "14px"), ("text-align", "left"), ("background-color", "#f2f2f2"), ("padding", "8px")]),
    dict(selector="td", props=[("font-size", "14px"), ("text-align", "left"), ("padding", "8px")]),
    dict(selector="tr:hover", props=[("background-color", "#f5f5f5")]),
]

# Apply CSS styles to the HTML table
styled_table = df.style.set_table_styles(table_styles)
# Define table header
table_header = "### Table A2: The input commodities and fuels included in SATIM.\n"

# Display table header
display(Markdown(table_header))

# Display the styled table
styled_table

### Table A2: The input commodities and fuels included in SATIM.