# 9. The Power Sector
### 9.2. Fuels

```{note}
Check the hide-cell/hide-input/remove-cell/remove-input functionality.
```

In [1]:
import pandas as pd
from IPython.display import Markdown, display

# Load the Excel file
excel_file = 'VT_REGION1_ELC.xlsx'

# Load the specified sheet
sheet_name = 'Commodities'
data_range = 'B7:F75'

# Read data from Excel, excluding the first row
df = pd.read_excel(excel_file, sheet_name=sheet_name, header=None, usecols="B:F", skiprows=7, nrows=69)

# Assign column names
df.columns = ['Commodity Code', 'Commodity Description', 'Commodity Unit', 'Commodity Set(Csets)', 'Timeslice level (CTSLvl)']

# Remove empty rows
df = df.dropna()

# Define CSS styles for the table
table_styles = [
    dict(selector="th", props=[("font-size", "14px"), ("text-align", "left"), ("background-color", "#f2f2f2"), ("padding", "8px")]),
    dict(selector="td", props=[("font-size", "14px"), ("text-align", "left"), ("padding", "8px")]),
    dict(selector="tr:hover", props=[("background-color", "#f5f5f5")]),
]

# Apply CSS styles to the HTML table
styled_table = df.style.set_table_styles(table_styles)
# Define table header
table_header = "### Table A2: The commodities and fuels included in the power sector of SATIM.\n"

# Display table header
display(Markdown(table_header))

# Display the styled table
styled_table

### Table A2: The commodities and fuels included in the power sector of SATIM.